Adaro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("login/", LoginView.as_view(template_name="accounts/login.html"), name="LoginView"),
    path("logout/", LogoutView.as_view(), name="LogoutView"),
    path("", include("app.urls"))
]

app/urls.py
from django.urls import path
from app.views import (
    MachineIncidentList,
    MachineIncidentCreate,
    MachineIncidentUpdate,
    MachineIncidentDelete,
    report
)


urlpatterns = [
    path("", MachineIncidentList.as_view(), name="MachineIncidentList"),
    path("create/", MachineIncidentCreate.as_view(), name="MachineIncidentCreate"),
    path("update/<int:pk>/", MachineIncidentUpdate.as_view(), name="MachineIncidentUpdate"),
    path("delete/<int:pk>/", MachineIncidentDelete.as_view(), name="MachineIncidentDelete"),
    path("report/", report, name="report"),
]

app/models.py
from django.db import models
from app.choices import MachineIncidentChoices


class MachineIncident(models.Model):
    machine = models.CharField(max_length=100, choices=MachineIncidentChoices.machine_choices)
    created_at = models.DateTimeField(auto_now_add=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(null=True, blank=True)
    shutdown_type = models.CharField(max_length=100, choices=MachineIncidentChoices.shutdown_type)
    shutdown_area = models.CharField(max_length=100, choices=MachineIncidentChoices.shutdown_area)
    description = models.TextField()

    def __str__(self):
        return self.shutdown_type

    def duration(self):
        if not self.end_time:
            return "Unfinished"
        else:
            return str(self.end_time - self.start_time)

    def duration_minute(self):
        if not self.end_time:
            return 0
        else:
            return (self.end_time - self.start_time).total_seconds() / 60

app/forms.py
from django import forms
from app.models import MachineIncident


class MachineIncidentForm(forms.ModelForm):
    class Meta:
        model = MachineIncident
        fields = ["machine", "start_time", "end_time", "shutdown_type", "shutdown_area", "description"]

app/views.py
from django.shortcuts import render
from django.views import generic
from app.models import MachineIncident
from django.urls import reverse_lazy
from app.forms import MachineIncidentForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils import timezone
import datetime
import pandas as pd
from calendar import monthrange
from app.choices import MachineIncidentChoices

@method_decorator(login_required, name="dispatch")
class MachineIncidentList(generic.ListView):
    model = MachineIncident
    template_name = "app/machine_incident_list.html"
    context_object_name = "incidents"


@method_decorator(login_required, name="dispatch")
class MachineIncidentCreate(generic.CreateView):
    model = MachineIncident
    template_name = "app/machine_incident_create.html"
    success_url = reverse_lazy("MachineIncidentList")
    form_class = MachineIncidentForm


@method_decorator(login_required, name="dispatch")
class MachineIncidentUpdate(generic.UpdateView):
    model = MachineIncident
    template_name = "app/machine_incident_create.html"
    context_object_name = "incident"
    form_class = MachineIncidentForm
    success_url = reverse_lazy("MachineIncidentList")


@method_decorator(login_required, name="dispatch")
class MachineIncidentDelete(generic.DeleteView):
    model = MachineIncident
    template_name = "app/machine_incident_delete.html"
    success_url = reverse_lazy("MachineIncidentList")


def report(request):
    data = []
    start_date = datetime.date(2020, 8, 1)
    end_date = datetime.datetime.now().date()
    month_list = [i.strftime("%b-%y") for i in pd.date_range(start=start_date, end=end_date, freq='MS')]
    for month in month_list:
        date = datetime.datetime.strptime(month, "%b-%y")
        total_time = monthrange(date.year, date.month)[1] * 24 * 60
        for machine in MachineIncidentChoices.machine_choices:
            down_time = 0
            incidents = MachineIncident.objects.filter(
                start_time__month=date.month,
                start_time__year=date.year,
                machine=machine[0]
            )
            for inc in incidents:
                down_time += inc.duration_minute()

            up_percent = (total_time - down_time) / total_time * 100
            down_percent = down_time / total_time * 100

            data.append({
                "month": month,
                "machine": machine[1],
                "up_percent": "%.3f" % up_percent,
                "down_percent": "%.3f" % down_percent
            })

    return render(request, "app/report.html", {"data": data})

templates/accounts/base_account.html
{% extends 'base.html' %}

{% load static %}


{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}

{% block navbar %}
{% endblock %}

{% block body %}

  <div class="container">

    <h1 class="text-center logo my-4">
      <a href={% url 'MachineIncidentList' %}>
          <img src="{% static 'img/adaro-logo.png' %}">
      </a>
    </h1>
    {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
    {% endfor %}
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

templates/accounts/login.html
{% extends 'accounts/base_account.html' %}


{% block content %}
  <div class="row justify-content-center mt-4">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Log in</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
          </form>
        </div>
      </div>
      <div class="text-center py-2">
      </div>
    </div>
  </div>
{% endblock %}

templates/app/machine_incident_create.html
{% extends "base.html" %}

{% block content %}
    <h1 class="mt-4">Create a new Incident</h1>

    <div class="card mt-4">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {% include 'includes/form.html' %}
                <button type="submit" class="btn btn-success">Save</button>
            </form>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script>
        $(function () {
            $("#id_start_time").datetimepicker({
              format: 'Y-m-d H:i',
            });
        });
        $(function () {
            $("#id_end_time").datetimepicker({
              format: 'Y-m-d H:i',
            });
        });
    </script>
{% endblock %}

templates/app/machine_incident_delete.html
{% extends "base.html" %}
{% block content %}
<div class="card mt-4">
    <div class="card-header">
        <h5 class="card-title">Delete Incident #{{object.machine}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Are you sure you want to delete <strong>{{ object.machine }}</strong> ?
            </div>
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
        <a href="{% url 'MachineIncidentList' %}"><button class="mt-2 btn btn-info">Back</button></a>

    </div>
</div>
{% endblock %}

templates/app/machine_incident_list.html
{% extends "base.html" %}

{% block content %}
 <h1 class="mt-4 mb-2">Machine Incident Lists</h1>
    <a href="{% url 'MachineIncidentCreate' %}">
        <button type="button" class="btn btn-primary mb-2">Craete Incident</button>
    </a>
<table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Machine</th>
                <th>Start Time</th>
                <th>End Date</th>
                <th>Duration</th>
                <th>Shutdown Type</th>
                <th>Shutdown Area</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        {% for incident in incidents %}
            <tr>
                <td>{{ incident.machine}}</td>
                <td>{{ incident.start_time }}</td>
                <td>{{ incident.end_time }}</td>
                <td>{{ incident.duration }}</td>
                <td>{{ incident.shutdown_type }}</td>
                <td>{{ incident.shutdown_area }}</td>
                <td>{{ incident.description }}</td>
                <td>
                      <div class="btn-group">
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Action
                      </button>
                      <div class="dropdown-menu">
                          <a class="dropdown-item" href="{% url 'MachineIncidentUpdate' incident.id %}">Edit</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'MachineIncidentDelete' incident.id %}">Delete</a>
                      </div>
                    </div>
                  </td>
            </tr>
        {% endfor %}
        </tbody>
</table>
{% endblock %}

{% block js %}
<script>
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>
{% endblock %}

templates/app/report.html
{% extends "base.html" %}

{% block content %}
 <h1 class="mt-4 mb-2">Fix Plant Monitoring</h1>

<table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Month</th>
                <th>Machine</th>
                <th>Up Percent</th>
                <th>Down Percent</th>
            </tr>
        </thead>
        <tbody>
        {% for d in data %}
            <tr>
                <td>{{ d.month }}</td>
                <td>{{ d.machine }}</td>
                <td>{{ d.up_percent }}</td>
                <td>{{ d.down_percent }}</td>
            </tr>
        {% endfor %}
        </tbody>
</table>
{% endblock %}

{% block js %}
<script>
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="{% static 'datetimepicker-master/jquery.datetimepicker.css' %}">
    <title>Adaro Project</title>
  </head>
  <body>
  {% block navbar %}
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'MachineIncidentList' %}"><img src="{% static 'img/adaro-logo.png' %}" width="150px"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'MachineIncidentList' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          {% if user.is_staff %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'report' %}">Report</a>
          </li>
            {% endif %}
        </ul>
      <ul class="navbar-nav ml-auto">

          {% if user.is_authenticated %}
          <a class="nav-link" href="#">{{ user.username }}</a>
          <a class="nav-link" href="{% url 'LogoutView' %}">Logout</a>
          {% else %}
          <a class="nav-link" href="{% url 'LoginView' %}">Login</a>
          {% endif %}

          </ul>
      </div>
    </nav>
  {% endblock %}
        <div class="container">
          {% block content %}
          {% endblock %}
        </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery.datetimepicker.full.js' %}"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
    {% block js %} {% endblock %}
  </body>
</html>

templates/includes/form.html
{% load form_tags widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}


{% for field in form %}
    <div class="form-group">
        {% if not field.is_hidden %}
        {{ field.label_tag }}
        {% endif %}
        {% render_field field class=field|input_class %}
        {% for error in field.errors %}
            <div class="invalid-feedback">
                {{ error }}
            </div>
        {% endfor %}
        {% if field.help_text %}
            <small class="form-text text-muted">
                {{ field.help_text }}
            </small>
        {% endif %}
    </div>
{% endfor %}